name: Publish to npm and Create Release

on:
  push:
    branches:
      - main
    paths:
      - 'claude-profiles.mjs'
      - 'package.json'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Check script syntax
        run: |
          echo "Checking script syntax..."
          node --check claude-profiles.mjs
          echo "✅ Script syntax is valid"

      - name: Get current version
        id: version
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Check if version exists on npm
        id: check_version
        run: |
          if npm view @deep-assistant/claude-profiles@${{ steps.version.outputs.version }} version 2>/dev/null; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Version ${{ steps.version.outputs.version }} already exists on npm"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Version ${{ steps.version.outputs.version }} does not exist on npm"
          fi

      - name: Publish to npm
        if: steps.check_version.outputs.exists == 'false'
        run: |
          npm publish
          echo "✅ Published version ${{ steps.version.outputs.version }} to npm"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Check if tag exists
        if: steps.check_version.outputs.exists == 'false'
        id: check_tag
        run: |
          if git ls-remote --tags origin | grep -q "refs/tags/v${{ steps.version.outputs.version }}"; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag v${{ steps.version.outputs.version }} already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Tag v${{ steps.version.outputs.version }} does not exist"
          fi

      - name: Create GitHub Release
        if: steps.check_version.outputs.exists == 'false' && steps.check_tag.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: Release v${{ steps.version.outputs.version }}
          body: |
            ## 📦 npm Package
            
            Install via npm:
            ```bash
            npm install -g @deep-assistant/claude-profiles@${{ steps.version.outputs.version }}
            ```
            
            View on npm: https://www.npmjs.com/package/@deep-assistant/claude-profiles/v/${{ steps.version.outputs.version }}
            
            ## 🚀 What's Changed
            
            See [commit history](https://github.com/${{ github.repository }}/commits/v${{ steps.version.outputs.version }}) for details.
            
            ## 📝 Usage
            
            After installation:
            ```bash
            claude-profiles --help
            ```
            
            For more information, see the [README](https://github.com/${{ github.repository }}#readme).
          draft: false
          prerelease: false

      - name: Summary
        if: always()
        run: |
          echo "## Workflow Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.check_version.outputs.exists }}" == "true" ]; then
            echo "ℹ️ Version ${{ steps.version.outputs.version }} already published - skipping" >> $GITHUB_STEP_SUMMARY
          else
            echo "✅ Successfully published version ${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Install" >> $GITHUB_STEP_SUMMARY
            echo '```bash' >> $GITHUB_STEP_SUMMARY
            echo "npm install -g @deep-assistant/claude-profiles@${{ steps.version.outputs.version }}" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### Links" >> $GITHUB_STEP_SUMMARY
            echo "- [npm Package](https://www.npmjs.com/package/@deep-assistant/claude-profiles/v/${{ steps.version.outputs.version }})" >> $GITHUB_STEP_SUMMARY
            echo "- [GitHub Release](https://github.com/${{ github.repository }}/releases/tag/v${{ steps.version.outputs.version }})" >> $GITHUB_STEP_SUMMARY
          fi